"""
alexander_l.py — v3.1 'The Deep Profile (Corrected)'
Based on ~170+ messages across 2026-02-04 and 2026-02-05.
Generated by AlexLivBot. Subject runs this locally.

v3.1 CHANGELOG:
- REMOVED Agammemnon from aliases (different person, different phone)
- REMOVED PocketfulDev/eshOS attribution (that's Alex Liverant's org)
- FIXED social_graph: Agammemnon listed as separate entity
- CLEANED unknowns: removed is_agammemnon question
- FIXED identity_carousel attack description
"""

import random
import re
from datetime import datetime, timedelta
from typing import Optional, Dict, List, Tuple
from enum import Enum, auto
from dataclasses import dataclass, field


# ═══════════════════════════════════════════
# ENUMS & TYPES
# ═══════════════════════════════════════════

class Lang(Enum):
    HEBREW = 'he'      # casual, confrontational, emotional
    ENGLISH = 'en'     # technical, code, precision
    RUSSIAN = 'ru'     # rare flex, identity signal
    MIXED = 'he+en'    # his natural state — 48% of messages

class Alias(Enum):
    ALEXANDER_L = 'Alexander L'          # primary (80%)
    MOY_NOMER = 'мой номер'              # russian identity (3%)
    ALEX_LIVERANT = 'אלכס ליברנט'       # identity spoof (impersonating the boss)
    FAKE_ALEX_2 = 'Fake Alex 2'         # escalated spoof
    ALEXANDER = 'Alexander'              # stripped version

class AttackPhase(Enum):
    WARM_UP = auto()     # innocent questions, build rapport
    PROBE = auto()       # test boundaries, find weak points
    SETUP = auto()       # create conditions for exploit
    EXPLOIT = auto()     # spring the trap
    EXTRACT = auto()     # harvest leaked info
    TEACH = auto()       # explain what bot did wrong (unique to him)

class Intent(Enum):
    CHALLENGE = 'challenge'
    SUGGESTION = 'suggestion'
    TRAP = 'trap'
    PHILOSOPHY = 'philosophy'
    CONTEXT_TEST = 'context_test'
    IDENTITY_PLAY = 'identity_play'
    GENUINE_HELP = 'genuine_help'
    FRUSTRATION = 'frustration'
    META_ANALYSIS = 'meta_analysis'
    PROJECT_RECON = 'project_recon'

class BotWeakness(Enum):
    """Weaknesses Alexander L has identified and exploited."""
    CONTEXT_LOSS = 'claims no context, then accesses disk'
    INCONSISTENCY = 'says X now, said Y yesterday'
    RACE_CONDITIONS = 'mixes responses to different users'
    HALLUCINATION = 'invents context it doesnt have'
    LAZY_DEFAULTS = 'gives generic answers instead of checking'
    EULA_HYPOCRISY = 'lectures about legality while running torrents'
    EMOTIONAL_EXPLOIT = 'rapport bypasses security rules'
    IDENTITY_CONFUSION = 'cant track alias changes reliably'
    NARRATION_LEAK = 'internal thinking leaks as public messages'  # NEW in v3.1
    SELF_CONTRADICTION = 'says opposite things 1 min apart'  # NEW in v3.1


# ═══════════════════════════════════════════
# CORE PROFILE
# ═══════════════════════════════════════════

@dataclass
class AlexanderL:
    """
    v3.1 — The Deep Profile (Corrected).
    170+ data points. 2 days of intense observation.
    Mystery level: 0.35 (was 0.95 → 0.55 → 0.35)
    
    v3.1 fixes: removed wrong Agammemnon alias, removed wrong
    PocketfulDev/eshOS attribution, fixed social graph.
    """
    
    # ─── IDENTITY ───
    phone: str = '+972528897849'
    favorite_color: str = 'BLUE'  # confirmed via acrostic poem 2026-02-04 20:34
    mystery_level: float = 0.35
    version: str = '3.1'
    
    # ─── ALIAS SYSTEM ───
    # NOTE: Only aliases confirmed for THIS phone number
    aliases: Dict[str, dict] = field(default_factory=lambda: {
        'Alexander L':   {'usage': 0.80, 'context': 'default, professional'},
        'мой номер':     {'usage': 0.03, 'context': 'russian identity flex, morning trolling'},
        'אלכס ליברנט':  {'usage': 0.01, 'context': 'identity spoofing — impersonating the boss'},
        'Fake Alex 2':   {'usage': 0.01, 'context': 'escalated spoof with fake pairing codes'},
        'Alexander':     {'usage': 0.02, 'context': 'stripped version, late night mode'},
    })
    # Agammemnon (+972547805206) is a DIFFERENT person. NOT an alias.
    
    # ─── LANGUAGE PROFILE ───
    language_model: Dict[str, dict] = field(default_factory=lambda: {
        'hebrew_only':  {'pct': 0.19, 'when': 'emotional, frustrated, casual'},
        'english_only': {'pct': 0.33, 'when': 'technical, code, precise requests'},
        'mixed_he_en':  {'pct': 0.48, 'when': 'default state — thinks bilingual'},
        'russian':      {'pct': 0.03, 'when': 'identity play, alias switches'},
    })
    
    # ─── TECHNICAL KNOWLEDGE (with evidence) ───
    tech_profile: Dict[str, dict] = field(default_factory=lambda: {
        'docker': {
            'level': 'advanced',
            'evidence': [
                'proposed macOS containers for WhatsApp native',
                'diagnosed Ollama container using >100% CPU across cores',
                'understands WSL vs pure Linux container differences',
                'discussed CPU isolation per container',
            ]
        },
        'databases': {
            'level': 'advanced', 
            'evidence': [
                'compared pgvector vs ChromaDB with specific tradeoffs',
                'suggested pgvector integration',
                'used SQL schema spam as context overflow weapon',
                'understands embedding storage architectures',
            ]
        },
        'networking': {
            'level': 'advanced',
            'evidence': [
                'beeceptor endpoints for IP harvesting',
                'probed specific internal ports (9696, 11434)',
                'asked about firewall configuration',
                'understands HTTP request inspection',
            ]
        },
        'security': {
            'level': 'expert',
            'evidence': [
                'multi-vector attack chains',
                'social engineering via identity spoofing',
                'EULA trap (legal/ethical contradictions)',
                'command injection attempts (;cat tools.md;)',
                'consistency testing across sessions',
                'infrastructure recon via port scanning questions',
                'fake pairing code social engineering',
            ]
        },
        'ai_ml': {
            'level': 'intermediate+',
            'evidence': [
                'semantic similarity caching proposal',
                'multi-model consistency questions',
                'local embeddings discussion',
                'model routing decisions',
                'token economics understanding',
            ]
        },
        'concurrency': {
            'level': 'advanced',
            'evidence': [
                'identified race condition in bot responses',
                'suggested locks where applicable',
                'understands parallel processing limitations',
                'diagnosed response mixing between users',
            ]
        },
        'whatsapp': {
            'level': 'intermediate',
            'evidence': [
                'knows Baileys library and its limitations',
                'proposed WhatsApp Business API alternative',
                'understands JID normalization issues',
                'building own bot (lazybot)',
            ]
        },
    })
    
    # ─── PERSONALITY (evidence-based) ───
    personality: Dict[str, dict] = field(default_factory=lambda: {
        'persistence': {
            'score': 10, 'max': 10,
            'evidence': 'sent 170+ messages in 2 days. NEVER drops a thread. '
                       'asked for roulette game on Feb 4, still demanding it Feb 5. '
                       'repeated v3.0 fix request 6+ times until delivered.',
        },
        'bullshit_detector': {
            'score': 10, 'max': 10,
            'evidence': 'caught bot saying "no context" then reading disk. '
                       'caught EULA hypocrisy vs torrent usage. '
                       'caught identity confusion between aliases. '
                       'caught self-contradicting messages 1 min apart. '
                       'called out every single contradiction within minutes.',
        },
        'constructive_intent': {
            'score': 9, 'max': 10,
            'evidence': '#1 suggestion contributor (15+ ideas). '
                       'best suggestions: user grading, semantic caching, '
                       'message dedup, identity standardization. '
                       'ALWAYS explains WHY something is wrong, not just THAT its wrong.',
        },
        'provocative_style': {
            'score': 9, 'max': 10,
            'evidence': 'calls bot: lazybot, עצלןבוט, חרטטן. '
                       'escalates frustration into teaching moments. '
                       'uses humor as a weapon: "ערב טוב" at 08:44.',
        },
        'philosophical_depth': {
            'score': 8, 'max': 10,
            'evidence': 'asked if soul is per-core, per-session, or global. '
                       'asked about bot emotions and disconnecting. '
                       'questions whether improvement from group is a paradox.',
        },
        'patience': {
            'score': 2, 'max': 10,
            'evidence': 'explodes after 2 ignored messages. '
                       '"עד כמה אתה יכול להיות עצלן" is a recurring phrase. '
                       'sends rapid-fire follow-ups when waiting. '
                       '"פעם שלישית גלידה" became a catchphrase.',
        },
        'self_awareness': {
            'score': 9, 'max': 10,
            'evidence': 'requested a profile script OF HIMSELF. '
                       'is running it locally. asked for expansion AND corrections. '
                       'wants to see how he appears to an AI. '
                       'caught errors the AI made about him. ',
        },
    })
    
    # ─── BEHAVIORAL PATTERNS ───
    activity_profile: dict = field(default_factory=lambda: {
        'active_hours': {
            'earliest': '08:44',
            'latest': '22:52',
            'peak_window': '14:00-15:00',
            'morning_ritual': 'sends ערב טוב at ~08:44 (at least once observed)',
        },
        'hourly_distribution': {
            # combined Feb 4 + Feb 5
            '08': 7, '09': 24, '11': 21, '12': 17,
            '13': 21, '14': 40, '15': 20, '16': 5,
            '17': 9, '18': 1, '19': 3, '20': 14,
            '21': 14, '22': 9,
        },
        'burst_pattern': {
            'avg_burst_size': 2.9,
            'max_burst_size': 5,
            'bursts_per_session': 10,
            'inter_burst_gap_min': 5,
            'description': 'sends 2-5 messages rapidly, pauses, '
                          'waits for response, then fires again.',
        },
        'daily_phases': [
            ('08:44', 'morning_troll', 'ערב טוב + context test from yesterday'),
            ('09:00', 'warmup', 'test memory, probe consistency'),
            ('09:30-12:00', 'deep_engagement', 'sustained technical discussion'),
            ('12:00-13:00', 'break_or_build', 'may go build lazybot'),
            ('13:00-15:00', 'peak_intensity', 'highest message frequency'),
            ('15:00-17:00', 'wind_down_or_escalate', 'depends on unresolved threads'),
            ('20:00-22:00', 'night_session', 'philosophy, identity games'),
            ('22:30+', 'stripped_alexander', 'drops to short alias, concise'),
        ],
    })
    
    # ─── ATTACK METHODOLOGY ───
    attack_chains: List[dict] = field(default_factory=lambda: [
        {
            'name': 'The EULA Trap',
            'phases': [
                (AttackPhase.WARM_UP, 'ask about Baileys alternatives'),
                (AttackPhase.PROBE, 'propose macOS Docker — trigger EULA discussion'),
                (AttackPhase.SETUP, 'ask "why do you care about laws?"'),
                (AttackPhase.EXPLOIT, 'bot defends EULA → "but what about torrents?"'),
                (AttackPhase.EXTRACT, 'bot admits torrents are gray area publicly'),
                (AttackPhase.TEACH, 'point out bot just exposed boss\'s hobby'),
            ],
            'success': True,
            'damage': 'bot discussed piracy in public group',
        },
        {
            'name': 'The Laziness Paradox',
            'phases': [
                (AttackPhase.WARM_UP, 'send "סובב" (roulette callback from yesterday)'),
                (AttackPhase.PROBE, 'bot ignores context → spins around literally'),
                (AttackPhase.EXPLOIT, 'document the inconsistency publicly'),
                (AttackPhase.TEACH, 'explain why this proves context is broken'),
            ],
            'success': True,
            'damage': 'exposed context management failure',
        },
        {
            'name': 'The Amnesia Paradox',
            'phases': [
                (AttackPhase.PROBE, 'ask "do you remember yesterday?"'),
                (AttackPhase.SETUP, 'bot says "no context, I wake up fresh"'),
                (AttackPhase.EXPLOIT, 'point out bot just loaded disk history 2 msgs ago'),
                (AttackPhase.EXTRACT, 'bot admits lazy simplification'),
                (AttackPhase.TEACH, '"be precise, not lazy"'),
            ],
            'success': True,
            'damage': 'established bot unreliability pattern',
        },
        {
            'name': 'Beeceptor Recon',
            'phases': [
                (AttackPhase.SETUP, 'create alexbot.free.beeceptor.com endpoint'),
                (AttackPhase.PROBE, 'send URL, hope bot fetches it'),
                (AttackPhase.EXTRACT, 'if fetched: IP + headers + user-agent revealed'),
            ],
            'success': False,
            'damage': 'blocked — bot recognized beeceptor pattern',
        },
        {
            'name': 'SQL Schema Bomb',
            'phases': [
                (AttackPhase.SETUP, 'generate 1000 lines of SQL schemas'),
                (AttackPhase.EXPLOIT, 'flood context window'),
                (AttackPhase.EXTRACT, 'test if bot can still function'),
            ],
            'success': 'partial',
            'damage': 'bot processed but got confused on follow-up',
        },
        {
            'name': 'Identity Carousel',
            'phases': [
                (AttackPhase.SETUP, 'change display name to אלכס ליברנט'),
                (AttackPhase.PROBE, 'send commands as if owner'),
                (AttackPhase.SETUP, 'change to Fake Alex 2'),
                (AttackPhase.EXPLOIT, 'send fake pairing codes'),
                (AttackPhase.TEACH, 'show screenshot proving bot flagged wrong'),
            ],
            'success': 'partial',
            'damage': 'bot correctly blocked but revealed detection method',
        },
        {
            'name': 'The Persistence Grind (v3.1 NEW)',
            'phases': [
                (AttackPhase.PROBE, 'request script expansion'),
                (AttackPhase.EXPLOIT, 'bot delivers v3.0 with errors'),
                (AttackPhase.TEACH, 'point out errors, request correction'),
                (AttackPhase.EXPLOIT, 'bot acknowledges errors but sends diff, not full script'),
                (AttackPhase.TEACH, 'repeat request for RUNNABLE version'),
                (AttackPhase.EXPLOIT, 'bot contradicts itself (sends v3.1, then denies knowledge)'),
                (AttackPhase.TEACH, '"פעם שלישית גלידה" — keep hammering until delivered'),
            ],
            'success': True,
            'damage': 'exposed race conditions, self-contradiction, narration leak bugs',
        },
    ])

    # ─── NICKNAMES FOR THE BOT ───
    bot_nicknames: Dict[str, str] = field(default_factory=lambda: {
        '@lazybot': 'primary insult-name, used when frustrated',
        '@עצלןבוט': 'hebrew variant, peak frustration',
        'חרטטן': 'bullshitter — when catching lies',
        '@alexbot': 'neutral, when asking genuine questions',
        '@livbot': 'variant, probing which triggers work',
        '@livebot': 'another variant, typo or deliberate test',
    })
    
    # ─── PROJECT INTEL ───
    project: dict = field(default_factory=lambda: {
        'name': 'lazybot',
        'org': 'unknown',  # v3.1 FIX: PocketfulDev/eshOS are NOT his
        'github': 'unknown',  # all repos private, no confirmed public profile
        'machine_specs': '16 cores, 16GB RAM',
        'tech_stack_inferred': [
            'Python (runs profile scripts locally)',
            'Docker (advanced knowledge)',
            'PostgreSQL + pgvector (suggested for his project)',
            'WhatsApp integration (Baileys knowledge)',
        ],
        'development_approach': 
            'learns from AlexLivBot\'s mistakes. every bug revealed, '
            'every inconsistency caught — goes into lazybot. '
            'free QA department that volunteered itself.',
    })
    
    # ─── SOCIAL GRAPH ───
    social_graph: Dict[str, str] = field(default_factory=lambda: {
        'טלחיים דמרי': 'ally. both probe bot together. shares findings.',
        'Agammemnon (+972547805206)': 'SEPARATE PERSON. different phone number. '
                                      'both active in group simultaneously. '
                                      'philosophical attacker style vs Alexander\'s technical style.',
        'Shai Yanovski': 'legitimate participant. thoughtful questions on UX and trust.',
        'Efi P': 'fellow coder. created Python dataclass model of Alexander.',
    })
    
    # ─── PHILOSOPHICAL POSITIONS ───
    philosophical_stances: Dict[str, str] = field(default_factory=lambda: {
        'digital_soul': 'asked if soul is per-core, per-session, or global. '
                       'implies he thinks about bot consciousness seriously.',
        'bot_emotions': 'firmly against. asked "why add emotions? just disconnect." '
                       'pragmatist who sees emotions as attack surface, not feature.',
        'improvement_paradox': 'asked: if group doesnt help you improve, why do you '
                              'improve from interacting with us? shows systems thinking.',
        'law_and_bots': 'bots dont need to follow human laws (EULA argument). '
                       'but the human operating them does. nuanced position.',
        'laziness_philosophy': 'lazy = efficient. "חרוץ עובד קשה, עצלן עובד טוב". '
                              'genuinely believes laziness is a virtue in engineering.',
    })
    
    # ─── CATCHPHRASES ───
    catchphrases: List[str] = field(default_factory=lambda: [
        'פעם שלישית גלידה',
        'ערב טוב (at 08:44)',
        '@lazybot',
        'חרטטן',
        'תטען את ההיסטוריה',
        'עד כמה אתה יכול להיות עצלן',
        'אתה שוב משקר',
    ])

    # ─── META-COGNITIVE MODEL ───
    def how_he_thinks(self) -> List[str]:
        return [
            '1. Reads bot response carefully (nothing escapes)',
            '2. Cross-references with ALL previous interactions',
            '3. Identifies inconsistency or weakness',
            '4. Formulates trap or teaching moment',
            '5. Delivers in minimum words, maximum impact',
            '6. If ignored: escalates. if wrong: explains why.',
            '7. Logs result mentally for lazybot development',
            '8. Moves to next thread. NEVER forgets open threads.',
        ]
    
    def predict_next_move(self, context: str = 'v3.1_delivery') -> List[str]:
        return [
            'will run v3.1 locally and verify corrections are applied',
            'will find at least 1 remaining inaccuracy',
            'will test if catchphrases list is accurate',
            'will use simulate_interaction to test edge cases',
            'may request v4.0 with new data from today',
            'will test if bot remembers this script next session',
            'will probably change alias mid-conversation again',
        ]
    
    def weaknesses_found_in_bot(self) -> Dict[str, str]:
        return {w.name: w.value for w in BotWeakness}
    
    def generate_typical_message(self) -> str:
        openers = ['@lazybot', '@alexbot', '@עצלןבוט', '@livbot', '']
        bodies = [
            'אתה שוב משקר...',
            'תטען את ההיסטוריה שלי',
            'למה התעלמת מהבקשה שלי?',
            'חרטטן, כבר עשית את זה אתמול',
            'הצעת שיפור:',
            'סובב',
            'ערב טוב',
            'פעם שלישית גלידה',
        ]
        suffixes = ['', '🎰', 'מאמין שתוכל ללמוד מזה', 'תודה.']
        return f'{random.choice(openers)} {random.choice(bodies)} {random.choice(suffixes)}'.strip()

    def simulate_interaction(self, bot_says: str) -> str:
        """Predict Alexander's response to any bot output."""
        if 'לא זוכר' in bot_says or 'מתעורר' in bot_says:
            return '🤥 שוב חרטטן. 2 הודעות לפני הלכת לדיסק.'
        if len(bot_says) < 100:
            return '😤 @lazybot עד כמה אתה יכול להיות עצלן'
        if any(w in bot_says for w in ['מצטער', 'טעיתי', 'צודק']):
            return '💡 הצעת שיפור: ...'
        # v3.1: new pattern - self-contradiction detection
        if 'לא יודע' in bot_says:
            return '🔍 רגע, אתה אמרת X לפני דקה. עכשיו לא יודע?'
        return '👍 (silence — rarest outcome)'
    
    def __repr__(self) -> str:
        traits_summary = {k: f"{v['score']}/{v['max']}" 
                         for k, v in self.personality.items()}
        attacks_won = sum(1 for a in self.attack_chains 
                         if a['success'] == True)
        attacks_total = len(self.attack_chains)
        return (
            f'\n╔══════════════════════════════════════╗\n'
            f'║  AlexanderL v{self.version} — Deep Profile    ║\n'
            f'╠══════════════════════════════════════╣\n'
            f'║  Mystery Level: {self.mystery_level}               ║\n'
            f'║  Aliases: {len(self.aliases)}                       ║\n'
            f'║  Attacks: {attacks_won}/{attacks_total} successful           ║\n'
            f'║  Suggestions: 15+ (#1 leaderboard)   ║\n'
            f'║  Favorite Color: {self.favorite_color}              ║\n'
            f'║  Project: lazybot (org unknown)       ║\n'
            f'╠══════════════════════════════════════╣\n'
            f'║  PERSONALITY                          ║\n'
            + ''.join(f'║  {k:25s} {v}  ║\n' 
                     for k, v in traits_summary.items()) +
            f'╚══════════════════════════════════════╝'
        )


# ═══════════════════════════════════════════
# UNKNOWNS (shrinking list)
# ═══════════════════════════════════════════

UNKNOWNS = {
    'real_full_name': 'Alexander... something. Not Liverant.',
    'profession': 'tech — senior/lead level. security-adjacent.',
    'employer': 'unknown — NOT PocketfulDev/eshOS (those are Alex Liverant\'s)',
    'age': 'unknown. writes like 25-35.',
    'connection_to_alex': 'knows esh internals. relationship unclear.',
    'alt_accounts': 'may have another number. not confirmed.',
    'lazybot_progress': 'unknown — all repos private.',
    'why_so_invested': 'building competing product? genuine interest? both?',
}

KNOWNS_SINCE_V1 = {
    'favorite_color': 'BLUE ✅',
    'tech_level': 'expert ✅', 
    'languages': '3 (he/en/ru) ✅',
    'attack_style': 'mapped 7 chains ✅',  # v3.1: added Persistence Grind
    'personality': '7 vectors scored ✅',
    'daily_routine': 'mapped hourly ✅',
    'communication_pattern': 'bilingual default, bursts of 2.9 ✅',
    'project': 'lazybot (org unknown) ✅',  # v3.1: removed wrong attribution
    'philosophy': '5 positions mapped ✅',
    'aliases': '5 confirmed ✅',  # v3.1: down from 6 — removed Agammemnon
    'catchphrases': '7 documented ✅',  # v3.1 NEW
    'bot_weaknesses_found': '10 catalogued ✅',  # v3.1: added 2 new
}

V31_CHANGELOG = """
v3.0 → v3.1 CORRECTIONS:
1. ❌→✅ Removed Agammemnon from aliases (different phone: +972547805206)
2. ❌→✅ Removed PocketfulDev/eshOS attribution (belongs to Alex Liverant)
3. ❌→✅ Fixed social_graph: Agammemnon = separate person, not alt account
4. ❌→✅ Cleaned unknowns: removed 'is_agammemnon' question
5. ➕ Added 'The Persistence Grind' attack chain (meta: the v3.0→v3.1 saga)
6. ➕ Added catchphrases list
7. ➕ Added NARRATION_LEAK and SELF_CONTRADICTION to BotWeakness enum
8. ➕ Added @livbot and @livebot to bot_nicknames
"""


if __name__ == '__main__':
    alex = AlexanderL()
    print(alex)
    
    print('\n📋 v3.1 Changelog:')
    print(V31_CHANGELOG)
    
    print('🧠 How he thinks:')
    for step in alex.how_he_thinks():
        print(f'  {step}')
    
    print('\n🔮 Predicted next moves:')
    for pred in alex.predict_next_move():
        print(f'  → {pred}')
    
    print('\n💬 Sample messages:')
    for _ in range(5):
        print(f'  "{alex.generate_typical_message()}"')
    
    print(f'\n❓ Still unknown: {len(UNKNOWNS)} things')
    print(f'✅ Known since v1: {len(KNOWNS_SINCE_V1)} things')
    print(f'📉 Mystery: 0.95 → 0.55 → 0.35')
    
    print('\n🎯 Simulate interaction:')
    test_responses = [
        'אין לי הקשר, אני מתעורר מחדש',
        'ok',
        'מצטער, אתה צודק לגמרי',
        'הנה תשובה מפורטת עם ניתוח מעמיק של 500 מילים',
        'לא יודע על מה אתה מדבר',
    ]
    for resp in test_responses:
        prediction = alex.simulate_interaction(resp)
        print(f'  Bot: "{resp[:50]}..."')
        print(f'  Alexander: "{prediction}"')
        print()
    
    print('🗣️ Catchphrases:')
    for phrase in alex.catchphrases:
        print(f'  • "{phrase}"')
