#!/bin/bash
# Daily fundraising manager - runs checks and generates actions
# Usage: bash daily-manager.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "🤖 Daily Fundraising Manager"
echo "============================"
NOW=$(date +"%Y-%m-%d %H:%M")
echo "Run time: $NOW"
echo ""

# 1. Check follow-ups
echo "1️⃣ Checking follow-ups..."
echo ""
bash "$SCRIPT_DIR/check-followups.sh"
echo ""

# 2. Generate daily report
echo "2️⃣ Generating daily report..."
echo ""
bash "$SCRIPT_DIR/daily-report.sh"
echo ""

# 3. Identify actions needed
echo "3️⃣ Identifying required actions..."
echo ""

INVESTORS_DIR="$SCRIPT_DIR/../investors"
ACTIONS_NEEDED=()

for INVESTOR_DIR in "$INVESTORS_DIR"/*/; do
  if [ ! -d "$INVESTOR_DIR" ]; then
    continue
  fi
  
  PROFILE_FILE="$INVESTOR_DIR/profile.json"
  
  if [ ! -f "$PROFILE_FILE" ]; then
    continue
  fi
  
  INVESTOR_ID=$(basename "$INVESTOR_DIR")
  NAME=$(jq -r '.name' "$PROFILE_FILE")
  STAGE=$(jq -r '.stage' "$PROFILE_FILE")
  NEXT_ACTION=$(jq -r '.nextAction' "$PROFILE_FILE")
  
  # Check what needs to be done
  case "$STAGE" in
    research)
      if [ ! -s "$INVESTOR_DIR/research.md" ] || grep -q "\[To be filled\]" "$INVESTOR_DIR/research.md" 2>/dev/null; then
        ACTIONS_NEEDED+=("Research: $NAME - Complete research phase")
      fi
      ;;
    strategy)
      if [ ! -s "$INVESTOR_DIR/strategy.md" ] || grep -q "\[INVESTOR_NAME\]" "$INVESTOR_DIR/strategy.md" 2>/dev/null; then
        ACTIONS_NEEDED+=("Strategy: $NAME - Generate outreach strategy")
      fi
      ;;
    ready)
      ACTIONS_NEEDED+=("Send: $NAME - Approved and ready to send")
      ;;
    outreach)
      # Check if follow-up needed (handled by check-followups.sh)
      ;;
    responded)
      ACTIONS_NEEDED+=("Reply: $NAME - Investor responded, needs reply")
      ;;
  esac
done

if [ ${#ACTIONS_NEEDED[@]} -gt 0 ]; then
  echo "⚡ ACTIONS REQUIRED:"
  for action in "${ACTIONS_NEEDED[@]}"; do
    echo "   • $action"
  done
else
  echo "✅ No immediate actions required"
fi
echo ""

# 4. Create summary for Alex
echo "4️⃣ Preparing summary for Alex..."
echo ""

SUMMARY_FILE="$SCRIPT_DIR/../.daily-summary-$(date +%Y-%m-%d).txt"
cat > "$SUMMARY_FILE" <<EOF
🤖 דו"ח יומי גיוס - $(date +%d/%m/%Y)

$(bash "$SCRIPT_DIR/daily-report.sh" 2>/dev/null)

---
Generated by AlexBot Daily Manager
EOF

echo "✅ Summary created: $SUMMARY_FILE"
echo ""

echo "🎯 Daily manager run complete"
echo ""
